package com.sakura.supermarket.view;

import java.awt.Cursor;
import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.ArrayList;
import java.util.List;

import javax.swing.ImageIcon;

import com.sakura.supermarket.model.ProductModel;

public class View_5_1_List extends javax.swing.JFrame {
/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
FundoTela tela;
    /**
     * Creates new form View_3_Register
     * 
     */


private List<ProductModel> productsToList = new ArrayList<ProductModel>();
private static List<ProductModel> list;
private int position;

public List<ProductModel> getProductToList(){
	
	return productsToList;
}

public static void setList(List<ProductModel> l) {
	list = l;
}


    public View_5_1_List() {
        initComponents();
         setExtendedState(MAXIMIZED_BOTH);
         setMinimumSize(new java.awt.Dimension(960, 540));
  
        
        
      
      


        
        


        
  
        
        
        addComponentListener(new ComponentAdapter(){
         @Override
            public void componentResized(ComponentEvent e) {
                double aux = getWidth() * 0.025;
                int text_size = (int) aux;
               
        
        

        jLabelDescription.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, text_size)); // NOI18N

        jLabelProduct.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, text_size)); // NOI18N
       
        
        
        
       
        
        ImageIcon icon = new ImageIcon("src/main/resources/images/button_yes.png");
         Image image = icon.getImage().getScaledInstance(jLabelButtonYes.getWidth(), jLabelButtonYes.getHeight(), Image.SCALE_SMOOTH);
         jLabelButtonYes.setIcon(new ImageIcon(image));
        jLabelButtonYes.setBackground(new java.awt.Color(255, 255, 255));
        
        icon = new ImageIcon("src/main/resources/images/button_no.png");
         image = icon.getImage().getScaledInstance(jLabelButtonNo.getWidth(), jLabelButtonNo.getHeight(), Image.SCALE_SMOOTH);
         jLabelButtonNo.setIcon(new ImageIcon(image));
        jLabelButtonNo.setBackground(new java.awt.Color(255, 255, 255));
            
            }
        
        
        });
        
 
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabelButtonYes = new javax.swing.JLabel();
        jLabelButtonNo = new javax.swing.JLabel();
        jLabelProduct = new javax.swing.JLabel();
        jLabelDescription = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(960, 540));
        
    	ProductModel product = list.get(0);
    	
    	jLabelDescription.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, 18)); // NOI18N
    	 jLabelDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      	jLabelDescription.setText("Existem " + product.getStock_quantity() + " produtos no estoque comprados em " + product.getPurchase_date() + ". Deseja colocar na lista?");

        jLabelButtonYes.setBackground(new java.awt.Color(255, 51, 0));
        jLabelButtonYes.setOpaque(true);
        jLabelButtonYes.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jLabelButtonYes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelButtonYesMouseClicked(evt);
            }
        });

        jLabelButtonNo.setBackground(new java.awt.Color(255, 51, 0));
        jLabelButtonNo.setOpaque(true);
        jLabelButtonNo.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jLabelButtonNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelButtonNoMouseClicked(evt);
            }
        });

        jLabelProduct.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, 18)); // NOI18N
        jLabelProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProduct.setText(product.getName());

     

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(51, 51, 51)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 852, Short.MAX_VALUE)
                        .addComponent(jLabelProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(54, 54, 54))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelButtonYes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabelButtonNo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(154, Short.MAX_VALUE)
                    .addComponent(jLabelProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelButtonYes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelButtonNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(72, Short.MAX_VALUE))
            );

        pack();
        
        
    }// </editor-fold>                        

    private void jLabelButtonYesMouseClicked(java.awt.event.MouseEvent evt) {
    	productsToList.add(list.get(position));
    	position++;
    	atualize();
      
    }                                            

    private void jLabelButtonNoMouseClicked(java.awt.event.MouseEvent evt) {                                            
    	position++;
    	atualize();
    } 
    
    private void atualize() {
    	  if(position < list.size()) {
          	setVisible(false);
          	ProductModel product = list.get(position);
          	jLabelProduct.setText(product.getName());
          	jLabelDescription.setText("Existem " + product.getStock_quantity() + " produtos no estoque comprados em " + product.getPurchase_date() + ". Deseja colocar na lista?");
          	setVisible(true);
          }else {
        	  View_5_2_List.setListProductsConfirm(productsToList);
        	  View_5_2_List.main(null);
        	  setVisible(false);
        	  
          }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_5_1_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_5_1_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_5_1_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_5_1_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_5_1_List().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabelButtonNo;
    private javax.swing.JLabel jLabelButtonYes;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelProduct;
    // End of variables declaration                   
}

