/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sakura.supermarket.view;

import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;

import javax.swing.ImageIcon;

/**
 *
 * @author User
 */
public class View_2_Menu extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;
	/**
	 * Creates new form Tela_1
	 * 
	 */
	FundoTela tela;

	public View_2_Menu() {

		tela = new FundoTela("src/main/resources/images/canva_menu.png");
		initComponents();
		setExtendedState(MAXIMIZED_BOTH);
		setMinimumSize(new java.awt.Dimension(960, 540));
		setLayout(new GridLayout());

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabelNumber2 = new javax.swing.JLabel();
		jLabelNumber3 = new javax.swing.JLabel();
		jLabelNumber1 = new javax.swing.JLabel();
		jLabelButtonRegister = new javax.swing.JLabel();
		jLabelButtonProducts = new javax.swing.JLabel();
		jLabelButtonList = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setMinimumSize(new java.awt.Dimension(960, 540));

		jLabelNumber2.setBackground(new java.awt.Color(255, 255, 255));

		jLabelNumber3.setBackground(new java.awt.Color(255, 255, 255));

		jLabelNumber1.setBackground(new java.awt.Color(255, 255, 255));

		jLabelButtonRegister.setBackground(new java.awt.Color(255, 255, 255));
		jLabelButtonRegister.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabelButtonRegisterMouseClicked(evt);
			}
		});

		jLabelButtonProducts.setBackground(new java.awt.Color(255, 255, 255));
		jLabelButtonProducts.setPreferredSize(null);
		jLabelButtonProducts.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabelButtonProductsMouseClicked(evt);
			}
		});

		jLabelButtonList.setBackground(new java.awt.Color(255, 255, 255));
		jLabelButtonList.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabelButtonListMouseClicked(evt);
			}
		});

		jLabelButtonRegister.setCursor(new Cursor(Cursor.HAND_CURSOR));
		jLabelButtonProducts.setCursor(new Cursor(Cursor.HAND_CURSOR));
		jLabelButtonList.setCursor(new Cursor(Cursor.HAND_CURSOR));

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(tela);
		tela.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(100, 100, 100)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jLabelNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabelNumber3, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabelNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addComponent(jLabelButtonProducts, javax.swing.GroupLayout.DEFAULT_SIZE, 400,
										Short.MAX_VALUE)
								.addComponent(jLabelButtonRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 400,
										Short.MAX_VALUE)
								.addComponent(jLabelButtonList, javax.swing.GroupLayout.DEFAULT_SIZE, 400,
										Short.MAX_VALUE))
						.addContainerGap(782, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap(148, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jLabelNumber1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
								.addComponent(jLabelButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap((int) (getHeight() * 0.03), (int) (getHeight() * 0.03), (int) (getHeight() * 0.03))
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabelNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabelButtonProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap((int) (getHeight() * 0.03), (int) (getHeight() * 0.03), (int) (getHeight() * 0.03))
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabelNumber3, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabelButtonList, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(123, Short.MAX_VALUE)));

		getContentPane().setLayout(new BorderLayout());
		getContentPane().add(tela, BorderLayout.CENTER);

		addComponentListener(new ComponentAdapter() {
			@Override
			public void componentResized(ComponentEvent e) {
				Dimension newSize = getSize();
				double aux = newSize.getWidth() * 0.15;
				int horizontal = (int) aux;
				aux = newSize.getWidth() * 0.42;
				int buttons = (int) aux;
				aux = getHeight() * 0.03;

				layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(horizontal, horizontal, horizontal)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jLabelNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelNumber3, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addComponent(jLabelButtonProducts, javax.swing.GroupLayout.DEFAULT_SIZE, 400,
												buttons)
										.addComponent(jLabelButtonRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 400,
												buttons)
										.addComponent(jLabelButtonList, javax.swing.GroupLayout.DEFAULT_SIZE, 400,
												buttons))
								.addContainerGap(782, Short.MAX_VALUE)));
				layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addContainerGap(148, Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jLabelNumber1, javax.swing.GroupLayout.DEFAULT_SIZE, 80,
												Short.MAX_VALUE)
										.addComponent(jLabelButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap((int) aux, (int) aux, (int) aux)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabelNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelButtonProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap((int) aux, (int) aux, (int) aux)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabelNumber3, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelButtonList, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(123, Short.MAX_VALUE)));
				ImageIcon icon = new ImageIcon("src/main/resources/images/image_button_register.png");
				Image image = icon.getImage().getScaledInstance(jLabelNumber1.getWidth(), jLabelNumber1.getHeight(),
						Image.SCALE_SMOOTH);
				jLabelNumber1.setIcon(new ImageIcon(image));
				jLabelNumber1.setBackground(new java.awt.Color(255, 255, 255));

				icon = new ImageIcon("src/main/resources/images/image_button_my_products.png");
				image = icon.getImage().getScaledInstance(jLabelNumber2.getWidth(), jLabelNumber2.getHeight(),
						Image.SCALE_SMOOTH);
				jLabelNumber2.setIcon(new ImageIcon(image));
				jLabelNumber2.setBackground(new java.awt.Color(255, 255, 255));

				icon = new ImageIcon("src/main/resources/images/image_button_generate_list.png");
				image = icon.getImage().getScaledInstance(jLabelNumber3.getWidth(), jLabelNumber3.getHeight(),
						Image.SCALE_SMOOTH);
				jLabelNumber3.setIcon(new ImageIcon(image));
				jLabelNumber3.setBackground(new java.awt.Color(255, 255, 255));

				icon = new ImageIcon("src/main/resources/images/button_register.png");
				image = icon.getImage().getScaledInstance(jLabelButtonRegister.getWidth(),
						jLabelButtonRegister.getHeight(), Image.SCALE_SMOOTH);
				jLabelButtonRegister.setIcon(new ImageIcon(image));
				jLabelButtonRegister.setBackground(new java.awt.Color(255, 255, 255));

				icon = new ImageIcon("src/main/resources/images/button_my_products.png");
				image = icon.getImage().getScaledInstance(jLabelButtonProducts.getWidth(),
						jLabelButtonProducts.getHeight(), Image.SCALE_SMOOTH);
				jLabelButtonProducts.setIcon(new ImageIcon(image));
				jLabelButtonProducts.setBackground(new java.awt.Color(255, 255, 255));

				icon = new ImageIcon("src/main/resources/images/button_generate_list.png");
				image = icon.getImage().getScaledInstance(jLabelButtonList.getWidth(), jLabelButtonList.getHeight(),
						Image.SCALE_SMOOTH);
				jLabelButtonList.setIcon(new ImageIcon(image));
				jLabelButtonList.setBackground(new java.awt.Color(255, 255, 255));

				
			}
		});
	}// </editor-fold>//GEN-END:initComponents

	private void jLabelButtonRegisterMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabelButtonRegisterMouseClicked
		new View_3_Register().setVisible(true);
		setVisible(false);
	}// GEN-LAST:event_jLabelButtonRegisterMouseClicked

	private void jLabelButtonProductsMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabelButtonProductsMouseClicked
		new View_4_0_Products().setVisible(true);
		setVisible(false);
	}// GEN-LAST:event_jLabelButtonProductsMouseClicked

	private void jLabelButtonListMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabelButtonListMouseClicked
		View_5_0_List.main(null);
		
	}// GEN-LAST:event_jLabelButtonListMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(View_2_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(View_2_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(View_2_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(View_2_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new View_2_Menu().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabelButtonList;
	private javax.swing.JLabel jLabelButtonProducts;
	private javax.swing.JLabel jLabelButtonRegister;
	private javax.swing.JLabel jLabelNumber1;
	private javax.swing.JLabel jLabelNumber2;
	private javax.swing.JLabel jLabelNumber3;
	// End of variables declaration//GEN-END:variables
}
