package com.sakura.supermarket.view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;

import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;

import com.sakura.supermarket.controller.ProductController;
import com.sakura.supermarket.model.ProductModel;

/**
 *
 * @author User
 */
public class View_4_0_Products extends javax.swing.JFrame {
/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
private FundoTela tela;
private ProductController productController = new ProductController();
private static ProductModel product = new ProductModel();

public static int getProductID() {
	
	return product.getId();
}
    /**
     * Creates new form View_4_Products
     */
    public View_4_0_Products() {
          setExtendedState(MAXIMIZED_BOTH);
         setMinimumSize(new java.awt.Dimension(960, 540));
        setLayout(new GridLayout());
         tela = new FundoTela("src/main/resources/images/canva_list.png");
         initComponents();
         
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProducts = new javax.swing.JTable();
        jLabelButtonBack = new javax.swing.JLabel();

       

  

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(960, 540));
        Object[][] dados = productController.tableOfProducts(productController.listOfProducts(1));
         String[] colunas = {"Id", "Nome"};
          DefaultTableModel model = new DefaultTableModel(dados, colunas) {
            /**
			 * 
			 */
			private static final long serialVersionUID = 1L;

			@Override
            public boolean isCellEditable(int row, int column) {
                return false;  // Torna todas as células não editáveis
            }
        };

    jTableProducts = new JTable(model) {
            /**
		 * 
		 */
		private static final long serialVersionUID = 1L;

			@Override
            public Component prepareRenderer(TableCellRenderer renderer, int row, int column) {
                Component comp = super.prepareRenderer(renderer, row, column);

                // Alterna a cor de fundo de linhas ímpares e pares
                if (!isRowSelected(row)) {
                    comp.setBackground(row % 2 == 0 ? new Color(255,255,255) : new Color(252,	233,	235));
                }

                return comp;
            }
        };
            
            
            jTableProducts.getColumnModel().getColumn(0).setPreferredWidth(200);
            jTableProducts.getColumnModel().getColumn(1).setPreferredWidth(800);
            jTableProducts.setRowHeight(50);
            jTableProducts.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, 18)); // NOI18N
            

        jScrollPane1.setViewportView(jTableProducts);
        jScrollPane1.getViewport().setBackground(Color.WHITE);
        
     
            
          JTableHeader tableHeader = jTableProducts.getTableHeader();
         

          tableHeader.setFont(new Font("Fredoka One", Font.PLAIN, 24)); 
          
          jTableProducts.addMouseListener(new java.awt.event.MouseAdapter() {
              public void mouseClicked(java.awt.event.MouseEvent evt) {
                  jTableProductsMouseClicked(evt);
              }
          });

          jLabelButtonBack.setCursor(new Cursor(Cursor.HAND_CURSOR));
          jLabelButtonBack.addMouseListener(new java.awt.event.MouseAdapter() {
              public void mouseClicked(java.awt.event.MouseEvent evt) {
                  jLabelButtonBackMouseClicked(evt);
              }
          });
          
          
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(tela);
        tela.setLayout(layout);
          layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabelButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

          getContentPane().setLayout(new BorderLayout());
        getContentPane().add(tela, BorderLayout.CENTER);
        
addComponentListener(new ComponentAdapter(){
        @Override
        public void componentResized(ComponentEvent e){
            
           ImageIcon icon = new ImageIcon("src/main/resources/images/button_back.png");
         Image image = icon.getImage().getScaledInstance(jLabelButtonBack.getWidth(), jLabelButtonBack.getHeight(), Image.SCALE_SMOOTH);
         jLabelButtonBack.setIcon(new ImageIcon(image));
        jLabelButtonBack.setBackground(new java.awt.Color(255, 255, 255));
    }
            });
        
    }// </editor-fold>                        

    private void jTableProductsMouseClicked(java.awt.event.MouseEvent evt) {                                            
    	Object value = jTableProducts.getValueAt(jTableProducts.getSelectedRow(), 0);
		
		product = productController.getProduct(value.toString());
		
		new View_4_1_View().setVisible(true);
		setVisible(false);
    }    
    
    private void jLabelButtonBackMouseClicked(java.awt.event.MouseEvent evt) {                                              
      new View_2_Menu().setVisible(true);
      setVisible(false);
    }  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_4_0_Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_4_0_Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_4_0_Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_4_0_Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_4_0_Products().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabelButtonBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProducts;
    // End of variables declaration                   
}

