package com.sakura.supermarket.view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;

import javax.swing.ImageIcon;

import com.sakura.supermarket.controller.CategoryController;
import com.sakura.supermarket.controller.ProductController;
import com.sakura.supermarket.model.ProductModel;

/**
 *
 * @author User
 */
public class View_4_2_Edit extends javax.swing.JFrame {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private FundoTela tela;
	private static ProductModel product;
	private CategoryController categoryController = new CategoryController();
	private ProductController productController = new ProductController();

	/**
	 * Creates new form View_3_Register
	 */
	public View_4_2_Edit() {
		product = productController.getProduct(String.valueOf(View_4_0_Products.getProductID()));
		setExtendedState(MAXIMIZED_BOTH);
		setMinimumSize(new java.awt.Dimension(960, 540));
		setLayout(new GridLayout());
		tela = new FundoTela("src/main/resources/images/canva_edit.png");

		initComponents();
		adapter();

	}

	private void adapter() {
		addComponentListener(new ComponentAdapter() {
			@Override
			public void componentResized(ComponentEvent e) {
				double aux = getWidth() * 0.025;
				int text_size = (int) aux;
				if (text_size > 25)
					text_size = 25;
				jLabelName.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, text_size)); // NOI18N

				jTextFieldNameValue.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, text_size)); // NOI18N

				jLabelDate.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, text_size)); // NOI18N

				jTextFieldDateValue.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, text_size)); // NOI18N

				jLabelQuantity.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, text_size)); // NOI18N

				jTextFieldQuantityValue.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, text_size)); // NOI18N

				jLabelDuration.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, text_size)); // NOI18N

				jTextFieldDurationValue.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, text_size)); // NOI18N

				jLabelStock.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, text_size)); // NOI18N

				jTextFieldStockValue.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, text_size)); // NOI18N

				jLabelMax.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, text_size)); // NOI18N

				jTextFieldMaxValue.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, text_size)); // NOI18N

				jLabelCategory.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, text_size)); // NOI18N

			

				ImageIcon icon = new ImageIcon("src/main/resources/images/button_save_edit.png");
				Image image = icon.getImage().getScaledInstance(jLabelButtonSave.getWidth(), jLabelButtonSave.getHeight(),
						Image.SCALE_SMOOTH);
				jLabelButtonSave.setIcon(new ImageIcon(image));
				jLabelButtonSave.setBackground(new java.awt.Color(255, 255, 255));

				icon = new ImageIcon("src/main/resources/images/button_cancel_edit.png");
				image = icon.getImage().getScaledInstance(jLabelButtonCancel.getWidth(), jLabelButtonCancel.getHeight(),
						Image.SCALE_SMOOTH);
				jLabelButtonCancel.setIcon(new ImageIcon(image));
				jLabelButtonCancel.setBackground(new java.awt.Color(255, 255, 255));

			}

		});
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		
		jLabelName = new javax.swing.JLabel();
		jLabelDate = new javax.swing.JLabel();
		jLabelQuantity = new javax.swing.JLabel();
		jLabelDuration = new javax.swing.JLabel();
		jLabelStock = new javax.swing.JLabel();
		jLabelMax = new javax.swing.JLabel();
		jLabelCategory = new javax.swing.JLabel();
		jComboBoxCategory = new javax.swing.JComboBox<>();
		jLabelButtonSave = new javax.swing.JLabel();
		jLabelButtonCancel = new javax.swing.JLabel();
		jTextFieldNameValue = new JTextFieldBackground("src/main/resources/images/background_edit_field_long.png");
		jTextFieldDateValue = new JTextFieldBackground("src/main/resources/images/background_edit_field_date.png");
		jTextFieldQuantityValue = new JTextFieldBackground("src/main/resources/images/background_edit_field_short.png");
		jTextFieldDurationValue = new JTextFieldBackground("src/main/resources/images/background_edit_field_short.png");
		jTextFieldStockValue = new JTextFieldBackground("src/main/resources/images/background_edit_field_short.png");
		jTextFieldMaxValue = new JTextFieldBackground("src/main/resources/images/background_edit_field_short.png");
		jLabelMessageError = new javax.swing.JLabel();
		jCheckBoxConfirm = new javax.swing.JCheckBox();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setMinimumSize(new java.awt.Dimension(960, 540));

		
		jLabelName.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, 20)); // NOI18N
		jLabelName.setText("Nome:");

		jLabelDate.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, 20)); // NOI18N
		jLabelDate.setText("Data de compra:");

		jLabelQuantity.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, 20)); // NOI18N
		jLabelQuantity.setText("Quantidade:");

		jLabelDuration.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, 20)); // NOI18N
		jLabelDuration.setText("Duração (dias):");

		jLabelStock.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, 20)); // NOI18N
		jLabelStock.setText("Estoque:");

		jLabelMax.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, 20)); // NOI18N
		jLabelMax.setText("Máx. de compra:");

		jLabelCategory.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, 20)); // NOI18N
		jLabelCategory.setText("Categoria:");

		jComboBoxCategory.setModel(
				new javax.swing.DefaultComboBoxModel<>(categoryController.allCategories()));
		jComboBoxCategory.setSelectedItem(product.getId_category() + " - " + product.getDescription_category());

		jLabelButtonSave.setOpaque(true);
		jLabelButtonSave.setCursor(new Cursor(Cursor.HAND_CURSOR));
		jLabelButtonSave.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabelButtonSaveMouseClicked(evt);
			}
		});

		jLabelButtonCancel.setOpaque(true);
		jLabelButtonCancel.setCursor(new Cursor(Cursor.HAND_CURSOR));
		jLabelButtonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabelButtonCancelMouseClicked(evt);
			}
		});

		jTextFieldNameValue.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, 18)); // NOI18N
		jTextFieldNameValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 7, 0, 7));
		jTextFieldNameValue.setText(product.getName());

		jTextFieldDateValue.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, 18)); // NOI18N
		jTextFieldDateValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 7, 0, 7));
		jTextFieldDateValue.setText(product.getPurchase_date());

		jTextFieldQuantityValue.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, 18)); // NOI18N
		jTextFieldQuantityValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 7, 0, 7));
		jTextFieldQuantityValue.setText(product.getQuantity());

		jTextFieldDurationValue.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, 18)); // NOI18N
		jTextFieldDurationValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 7, 0, 7));
		jTextFieldDurationValue.setText(String.valueOf(product.getDuration()));

		jTextFieldStockValue.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, 18)); // NOI18N
		jTextFieldStockValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 7, 0, 7));
		jTextFieldStockValue.setText(String.valueOf(product.getStock_quantity()));

		jTextFieldMaxValue.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, 18)); // NOI18N
		jTextFieldMaxValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 7, 0, 7));
		jTextFieldMaxValue.setText(String.valueOf(product.getMax_purchase()));

		jLabelMessageError.setBackground(new java.awt.Color(255, 255, 255));
		jLabelMessageError.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
		jLabelMessageError.setForeground(new java.awt.Color(255, 0, 0));
		
		jCheckBoxConfirm.setText("Confirmar antes de colocar na lista");
		if(product.isConfirm())
			jCheckBoxConfirm.setSelected(true);
		else
			jCheckBoxConfirm.setSelected(false);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(tela);
		tela.setLayout(layout);
		 layout.setHorizontalGroup(
		            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addGroup(layout.createSequentialGroup()
		                .addContainerGap(53, Short.MAX_VALUE)
		                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
		                    .addComponent(jCheckBoxConfirm, javax.swing.GroupLayout.Alignment.LEADING)
		                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
		                        .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
		                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                        .addComponent(jTextFieldNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
		                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
		                        .addComponent(jLabelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
		                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                        .addComponent(jTextFieldDateValue, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
		                    .addComponent(jLabelMessageError, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
		                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
		                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
		                            .addComponent(jLabelCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		                                .addGroup(layout.createSequentialGroup()
		                                    .addComponent(jLabelQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
		                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                                    .addComponent(jTextFieldQuantityValue, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
		                                .addGroup(layout.createSequentialGroup()
		                                    .addComponent(jLabelStock, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
		                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                                    .addComponent(jTextFieldStockValue, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
		                        .addGap(50, 50, 50)
		                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		                            .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
		                            .addGroup(layout.createSequentialGroup()
		                                .addComponent(jLabelMax, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
		                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                                .addComponent(jTextFieldMaxValue, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
		                            .addGroup(layout.createSequentialGroup()
		                                .addComponent(jLabelDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
		                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		                                .addComponent(jTextFieldDurationValue, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
		                .addContainerGap(54, Short.MAX_VALUE))
		            .addGroup(layout.createSequentialGroup()
		                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		                .addComponent(jLabelButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
		                .addGap(18, 18, 18)
		                .addComponent(jLabelButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
		                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		        );
		        layout.setVerticalGroup(
		            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		            .addGroup(layout.createSequentialGroup()
		                .addContainerGap(34, Short.MAX_VALUE)
		                .addComponent(jLabelMessageError, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
		                .addGap(50, 50, 50)
		                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		                    .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
		                    .addComponent(jTextFieldNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
		                .addGap(18, 18, 18)
		                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		                    .addComponent(jTextFieldDateValue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
		                    .addComponent(jLabelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
		                .addGap(18, 18, 18)
		                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		                    .addComponent(jLabelQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
		                    .addComponent(jTextFieldQuantityValue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
		                    .addComponent(jLabelDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
		                    .addComponent(jTextFieldDurationValue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
		                .addGap(18, 18, 18)
		                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		                    .addComponent(jLabelStock, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
		                    .addComponent(jTextFieldStockValue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
		                    .addComponent(jLabelMax, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
		                    .addComponent(jTextFieldMaxValue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
		                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
		                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		                    .addComponent(jLabelCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
		                    .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
		                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
		                .addComponent(jCheckBoxConfirm)
		                .addGap(18, 18, Short.MAX_VALUE)
		                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		                    .addComponent(jLabelButtonSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
		                    .addComponent(jLabelButtonCancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
		                .addContainerGap(72, Short.MAX_VALUE))
		        );


		getContentPane().setLayout(new BorderLayout());
		getContentPane().add(tela, BorderLayout.CENTER);
	}// </editor-fold>

	private void jLabelButtonSaveMouseClicked(java.awt.event.MouseEvent evt) {
		if(!productController.editProduct(product, jTextFieldNameValue.getText(), jComboBoxCategory.getSelectedItem().toString(), jTextFieldQuantityValue.getText(), jTextFieldDurationValue.getText(), jTextFieldStockValue.getText(), jTextFieldMaxValue.getText(), jTextFieldDateValue.getText(), jCheckBoxConfirm.isSelected())) {
			jLabelMessageError.setText(productController.getMessageError());
		}else {
			new View_4_1_View().setVisible(true);
			setVisible(false);
		}
	}

	private void jLabelButtonCancelMouseClicked(java.awt.event.MouseEvent evt) {
		new View_4_1_View().setVisible(true);
		setVisible(false);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(View_4_2_Edit.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(View_4_2_Edit.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(View_4_2_Edit.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(View_4_2_Edit.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new View_4_2_Edit().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	 private javax.swing.JCheckBox jCheckBoxConfirm;
	private javax.swing.JComboBox<String> jComboBoxCategory;
	private javax.swing.JLabel jLabelButtonCancel;
	private javax.swing.JLabel jLabelButtonSave;
	private javax.swing.JLabel jLabelCategory;
	private javax.swing.JLabel jLabelDate;
	private javax.swing.JLabel jLabelDuration;
	private javax.swing.JLabel jLabelMax;
	private javax.swing.JLabel jLabelMessageError;
	private javax.swing.JLabel jLabelName;
	private javax.swing.JLabel jLabelQuantity;
	private javax.swing.JLabel jLabelStock;
	private javax.swing.JTextField jTextFieldDateValue;
	private javax.swing.JTextField jTextFieldDurationValue;
	private javax.swing.JTextField jTextFieldMaxValue;
	private javax.swing.JTextField jTextFieldNameValue;
	private javax.swing.JTextField jTextFieldQuantityValue;
	private javax.swing.JTextField jTextFieldStockValue;
	// End of variables declaration
}
