package com.sakura.supermarket.view;

import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;

import javax.swing.ImageIcon;

import com.sakura.supermarket.controller.ProductController;
import com.sakura.supermarket.model.ProductModel;

/**
 *
 * @author User
 */
public class View_4_1_View extends javax.swing.JFrame {
	/**
		 * 
		 */
	private static final long serialVersionUID = 1L;
	private FundoTela tela;
	private static ProductModel product;
	private ProductController productController = new ProductController();
	
	

	/**
	 * Creates new form View_4_1_Edit
	 */
	public View_4_1_View() {
		product = productController.getProduct(String.valueOf(View_4_0_Products.getProductID()));
		setExtendedState(MAXIMIZED_BOTH);
		setMinimumSize(new java.awt.Dimension(960, 628));
		setLayout(new GridLayout());

		tela = new FundoTela("src/main/resources/images/canva_view.png");

		initComponents();
		resizable();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabelDateValue = new javax.swing.JLabel();
		jLabelDateTop = new javax.swing.JLabel();
		jLabelButtonBack = new javax.swing.JLabel();
		jLabelID = new javax.swing.JLabel();
		jLabelIDValue = new javax.swing.JLabel();
		jLabelName = new javax.swing.JLabel();
		jLabelNameValue = new javax.swing.JLabel();
		jLabelCategory = new javax.swing.JLabel();
		jLabelCategoryValue = new javax.swing.JLabel();
		jLabelQuantity = new javax.swing.JLabel();
		jLabelQuantityValue = new javax.swing.JLabel();
		jLabelDuration = new javax.swing.JLabel();
		jLabelDurationValue = new javax.swing.JLabel();
		jLabelStock = new javax.swing.JLabel();
		jLabelStockValue = new javax.swing.JLabel();
		jLabelMax = new javax.swing.JLabel();
		jLabelMaxValue = new javax.swing.JLabel();
		jLabelButtonDelete = new javax.swing.JLabel();
		jLabelButtonEdit = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setMinimumSize(new java.awt.Dimension(960, 540));

		jLabelID.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 1, 18)); // NOI18N
		jLabelID.setText("ID:");

		jLabelIDValue.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, 18)); // NOI18N
		jLabelIDValue.setText(String.valueOf(product.getId()));
		jLabelIDValue.setForeground(new java.awt.Color(242, 146, 157));

		jLabelButtonBack.setCursor(new Cursor(Cursor.HAND_CURSOR));
		jLabelButtonDelete.setCursor(new Cursor(Cursor.HAND_CURSOR));
		jLabelButtonEdit.setCursor(new Cursor(Cursor.HAND_CURSOR));

		jLabelButtonDelete.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabelButtonDeleteMouseClicked(evt);
			}
		});

		jLabelButtonEdit.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabelButtonEditMouseClicked(evt);
			}
		});

		jLabelName.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 1, 18)); // NOI18N
		jLabelName.setText("Nome:");

		jLabelNameValue.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, 18)); // NOI18N
		jLabelNameValue.setForeground(new java.awt.Color(242, 146, 157));
		jLabelNameValue.setText(product.getName());

		jLabelCategory.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 1, 18)); // NOI18N
		jLabelCategory.setText("Categoria:");

		jLabelCategoryValue.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, 18)); // NOI18N
		jLabelCategoryValue.setForeground(new java.awt.Color(242, 146, 157));
		jLabelCategoryValue.setText(product.getDescription_category());

		jLabelMaxValue.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, 18)); // NOI18N
		jLabelMaxValue.setForeground(new java.awt.Color(242, 146, 157));
		jLabelMaxValue.setText(String.valueOf(product.getMax_purchase()));

		jLabelMax.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 1, 18)); // NOI18N
		jLabelMax.setText("Máximo de compra:");

		jLabelStock.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 1, 18)); // NOI18N
		jLabelStock.setText("Estoque:");

		jLabelStockValue.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, 18)); // NOI18N
		jLabelStockValue.setForeground(new java.awt.Color(242, 146, 157));
		jLabelStockValue.setText(String.valueOf(product.getStock_quantity()));

		jLabelDateTop.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 1, 18)); // NOI18N
		jLabelDateTop.setText("Data de compra:");

		jLabelButtonBack.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabelButtonBackMouseClicked(evt);
			}
		});

		jLabelQuantity.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 1, 18)); // NOI18N
		jLabelQuantity.setText("Quantidade (kg/unidade):");

		jLabelQuantityValue.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, 18)); // NOI18N
		jLabelQuantityValue.setForeground(new java.awt.Color(242, 146, 157));
		jLabelQuantityValue.setText(product.getQuantity());

		jLabelDuration.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 1, 18)); // NOI18N
		jLabelDuration.setText("Duração:");

		jLabelDurationValue.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, 18)); // NOI18N
		jLabelDurationValue.setForeground(new java.awt.Color(242, 146, 157));
		jLabelDurationValue.setText(String.valueOf(product.getDuration()) + " dias");

		jLabelDateValue.setText(product.getPurchase_date());
		jLabelDateValue.setBackground(new java.awt.Color(198, 235, 240));
		jLabelDateValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelDateValue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(67, 67, 67), 1, true));
		jLabelDateValue.setOpaque(true);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(tela);
		tela.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(50, 50, 50).addComponent(jLabelButtonBack,
						javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(10, 10, 10)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabelIDValue, javax.swing.GroupLayout.PREFERRED_SIZE,
														325, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 325,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jLabelButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(jLabelButtonDelete,
												javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup()
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabelDateTop, javax.swing.GroupLayout.PREFERRED_SIZE,
														181, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabelDateValue, javax.swing.GroupLayout.PREFERRED_SIZE,
														181, javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addGap(50, 50, 50))
						.addGroup(layout.createSequentialGroup().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addComponent(jLabelStockValue,
										javax.swing.GroupLayout.PREFERRED_SIZE, 100,
										javax.swing.GroupLayout.PREFERRED_SIZE).addGap(275, 275, 275))
								.addGroup(layout.createSequentialGroup().addGroup(layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addComponent(jLabelStock, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jLabelQuantity, javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jLabelName, javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jLabelNameValue, javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
										.addComponent(jLabelQuantityValue, javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.PREFERRED_SIZE, 100,
												javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(0, 0, Short.MAX_VALUE)))
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabelMax, javax.swing.GroupLayout.PREFERRED_SIZE, 325,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(jLabelCategoryValue, javax.swing.GroupLayout.DEFAULT_SIZE,
														325, Short.MAX_VALUE)
												.addComponent(jLabelDurationValue,
														javax.swing.GroupLayout.PREFERRED_SIZE, 100,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabelDuration, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLabelCategory, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addComponent(jLabelMaxValue, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(0, 156, Short.MAX_VALUE)))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(100, 100, 100)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jLabelButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup()
										.addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabelIDValue, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabelCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabelNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabelCategoryValue, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabelQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabelDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabelQuantityValue, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabelDurationValue, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabelStock, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabelMax, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabelStockValue, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabelMaxValue, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(24, 24, 24)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(layout.createSequentialGroup()
										.addComponent(jLabelDateTop, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(0, 0, 0).addComponent(jLabelDateValue,
												javax.swing.GroupLayout.PREFERRED_SIZE, 49,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(jLabelButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 49,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(40, 40, 40)));

		getContentPane().setLayout(new BorderLayout());
		getContentPane().add(tela, BorderLayout.CENTER);
	}// </editor-fold>

	private void resizable() {
		addComponentListener(new ComponentAdapter() {
			@Override
			public void componentResized(ComponentEvent e) {

				double aux = getWidth() * 0.025;
				int text_size = (int) aux;
				if (text_size > 30)
					text_size = 30;

				jLabelID.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, text_size)); // NOI18N

				jLabelIDValue.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, text_size)); // NOI18N

				jLabelName.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, text_size)); // NOI18N

				jLabelNameValue.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, text_size)); // NOI18N

				jLabelDateTop.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, text_size)); // NOI18N

				jLabelDateValue.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, text_size)); // NOI18N

				jLabelQuantity.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, text_size)); // NOI18N

				jLabelQuantityValue.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, text_size)); // NOI18N

				jLabelDuration.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, text_size)); // NOI18N

				jLabelDurationValue.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, text_size)); // NOI18N

				jLabelStock.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, text_size)); // NOI18N

				jLabelStockValue.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, text_size)); // NOI18N

				jLabelMax.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, text_size)); // NOI18N

				jLabelMaxValue.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, text_size)); // NOI18N

				jLabelCategory.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, text_size)); // NOI18N

				jLabelCategoryValue.setFont(new java.awt.Font("JaneCapsBoldW00-Regular", 0, text_size)); // NOI18N

				ImageIcon icon = new ImageIcon("src/main/resources/images/button_edit.png");
				Image image = icon.getImage().getScaledInstance(jLabelButtonEdit.getWidth(),
						jLabelButtonEdit.getHeight(), Image.SCALE_SMOOTH);
				jLabelButtonEdit.setIcon(new ImageIcon(image));
				jLabelButtonEdit.setBackground(new java.awt.Color(255, 255, 255));

				icon = new ImageIcon("src/main/resources/images/button_delete.png");
				image = icon.getImage().getScaledInstance(jLabelButtonDelete.getWidth(), jLabelButtonDelete.getHeight(),
						Image.SCALE_SMOOTH);
				jLabelButtonDelete.setIcon(new ImageIcon(image));
				jLabelButtonDelete.setBackground(new java.awt.Color(255, 255, 255));

				icon = new ImageIcon("src/main/resources/images/button_back.png");
				image = icon.getImage().getScaledInstance(jLabelButtonBack.getWidth(), jLabelButtonBack.getHeight(),
						Image.SCALE_SMOOTH);
				jLabelButtonBack.setIcon(new ImageIcon(image));
				jLabelButtonBack.setBackground(new java.awt.Color(255, 255, 255));

				icon = new ImageIcon("src/main/resources/images/date_view_top.png");
				image = icon.getImage().getScaledInstance(jLabelDateTop.getWidth(), jLabelDateTop.getHeight(),
						Image.SCALE_SMOOTH);
				jLabelDateTop.setIcon(new ImageIcon(image));
				jLabelDateTop.setBackground(new java.awt.Color(255, 255, 255));

				aux = getHeight() * 0.32;
				int distance = (int) aux;

				javax.swing.GroupLayout layout = new javax.swing.GroupLayout(tela);
				tela.setLayout(layout);
				layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(50, 50, 50)
								.addComponent(jLabelButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 49,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(10, 10, 10)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup().addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup().addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabelIDValue,
																javax.swing.GroupLayout.PREFERRED_SIZE, 325,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE,
																325, javax.swing.GroupLayout.PREFERRED_SIZE))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jLabelButtonEdit,
																javax.swing.GroupLayout.PREFERRED_SIZE, 30,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(18, 18, 18).addComponent(jLabelButtonDelete,
																javax.swing.GroupLayout.PREFERRED_SIZE, 30,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(layout.createSequentialGroup()
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jLabelDateTop,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 181,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jLabelDateValue,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 181,
																		javax.swing.GroupLayout.PREFERRED_SIZE))))
												.addGap(50, 50, 50))
										.addGroup(layout.createSequentialGroup().addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup()
														.addComponent(jLabelStockValue,
																javax.swing.GroupLayout.PREFERRED_SIZE, 100,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(275, 275, 275))
												.addGroup(layout.createSequentialGroup().addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addComponent(jLabelStock, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jLabelQuantity,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jLabelName,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jLabelNameValue,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE, 325,
																Short.MAX_VALUE)
														.addComponent(jLabelQuantityValue,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.PREFERRED_SIZE, 100,
																javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGap(0, 0, Short.MAX_VALUE)))
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabelMax, javax.swing.GroupLayout.PREFERRED_SIZE,
																325, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING,
																		false)
																.addComponent(jLabelCategoryValue,
																		javax.swing.GroupLayout.DEFAULT_SIZE, 325,
																		Short.MAX_VALUE)
																.addComponent(jLabelDurationValue,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 100,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jLabelDuration,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(jLabelCategory,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE))
														.addComponent(jLabelMaxValue,
																javax.swing.GroupLayout.PREFERRED_SIZE, 100,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(0, 156, Short.MAX_VALUE)))));
				layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(distance, distance, distance).addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jLabelButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup()
										.addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabelIDValue, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabelNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelCategoryValue, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabelQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabelQuantityValue, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelDurationValue, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabelStock, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelMax, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabelStockValue, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabelMaxValue, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24,
										Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(layout.createSequentialGroup()
												.addComponent(jLabelDateTop, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(0, 0, 0).addComponent(jLabelDateValue,
														javax.swing.GroupLayout.PREFERRED_SIZE, 49,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(jLabelButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 49,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(40, Short.MAX_VALUE)));

			}

		});
	}

	private void jLabelButtonBackMouseClicked(java.awt.event.MouseEvent evt) {
		new View_4_0_Products().setVisible(true);
		setVisible(false);
	}

	private void jLabelButtonEditMouseClicked(java.awt.event.MouseEvent evt) {
		new View_4_2_Edit().setVisible(true);
		setVisible(false);
	}

	private void jLabelButtonDeleteMouseClicked(java.awt.event.MouseEvent evt) {
		productController.deleteProduct(product.getId());
		new View_4_0_Products().setVisible(true);
		setVisible(false);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(View_4_1_View.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(View_4_1_View.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(View_4_1_View.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(View_4_1_View.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new View_4_1_View().setVisible(true);
			}
		});
	}

	private javax.swing.JLabel jLabelButtonBack;
	private javax.swing.JLabel jLabelButtonDelete;
	private javax.swing.JLabel jLabelButtonEdit;
	private javax.swing.JLabel jLabelCategory;
	private javax.swing.JLabel jLabelCategoryValue;
	private javax.swing.JLabel jLabelDateTop;
	private javax.swing.JLabel jLabelDateValue;
	private javax.swing.JLabel jLabelDuration;
	private javax.swing.JLabel jLabelDurationValue;
	private javax.swing.JLabel jLabelID;
	private javax.swing.JLabel jLabelIDValue;
	private javax.swing.JLabel jLabelMax;
	private javax.swing.JLabel jLabelMaxValue;
	private javax.swing.JLabel jLabelName;
	private javax.swing.JLabel jLabelNameValue;
	private javax.swing.JLabel jLabelQuantity;
	private javax.swing.JLabel jLabelQuantityValue;
	private javax.swing.JLabel jLabelStock;
	private javax.swing.JLabel jLabelStockValue;
	// End of variables declaration
}
